modLoader = "javafml"
loaderVersion = "${neo_loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/Khajiitos/SussyEnderEyes/issues"

[[mods]]
modId = "sussyendereyes"
version = "${version}"
logoFile="icon.png"
displayName = "Sussy Ender Eyes"
authors = "Khajiitos"
displayURL="https://github.com/Khajiitos/SussyEnderEyes"
description = '''Makes placing ender eyes in end portal frames play the Among Us drip melody.'''
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config="sussyendereyes.mixins.json"

[[dependencies.sussyendereyes]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.sussyendereyes]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"